# Paso 6.- Otros indicadores precio PT-FR

## Obtener otro indicadores

Se van a obtener los siguientes indicadores:
  -   indicators_600  # Precio mercado SPOT Diario para PT y FR
  
  
## Precio de Portugal

In [2]:
from ESIOS import *
from matplotlib import pyplot as plt

if __name__ == '__main__':
    # Request arguments
    start_ = '2015-09-31T00:00:00'
    #end_ = '2015-10-02T00:00:00'
    end_ = '2019-08-01T00:00:00'

    token = '874b2aeaf4071f8db7085e0ca6aa88ede7e2992360fc0d6ad7af625b30b9e3bf'
    esios = ESIOS(token)

    indicators_ = list()
    indicators_.append(600)  # Precio mercado SPOT Diario

    names = esios.get_names(indicators_)
    dfmul, df_list, names = esios.get_multiple_series(indicators_,'pt', start_, end_)
    df = dfmul[names]  # get the actual series and neglect the rest of the info

Getting the indicators...
Parsing Precio mercado SPOT Diario

In [3]:
df.head()

                          Precio mercado SPOT Diario
2015-09-30 22:00:00+00:00                      56.65
2015-09-30 23:00:00+00:00                       53.5
2015-10-01 00:00:00+00:00                      49.69
2015-10-01 01:00:00+00:00                       49.1
2015-10-01 02:00:00+00:00                      51.25

In [4]:
from datetime import datetime

df_temp_hour = df
df_temp_hour['date'] = pd.to_datetime(df_temp_hour.index)
df_temp_hour['date_timestamp'] = df_temp_hour['date'].apply(lambda x:  datetime.timestamp(x))
df_temp_hour.head()

/Users/davidcerezallanda/.conda/envs/practicaspy36/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/davidcerezallanda/.conda/envs/practicaspy36/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

,Precio mercado SPOT Diario,date,date_timestamp
2015-09-30 22:00:00+00:00,56.65,2015-09-30 22:00:00+00:00,1.443650e+09
2015-09-30 23:00:00+00:00,53.5,2015-09-30 23:00:00+00:00,1.443654e+09
2015-10-01 00:00:00+00:00,49.69,2015-10-01 00:00:00+00:00,1.443658e+09
2015-10-01 01:00:00+00:00,49.1,2015-10-01 01:00:00+00:00,1.443661e+09
2015-10-01 02:00:00+00:00,51.25,2015-10-01 02:00:00+00:00,1.443665e+09

In [5]:
data_total = pd.read_csv("data_total.csv") 
data_total.head()

,Unnamed: 0,fecha,PVPC_DEF,PVPC_2_PED_NOC,PVPC_ELEC_NOC,date_timestamp,Demanda,Eolica,Nuclear,Solar,...,Precio de Regulación Secundaria subir,Precio de Regulación Secundaria bajar,Precio mercado SPOT Diario,Demanda real,Generación prevista Solar,Saldo total interconexiones programa p48,Generación programada P48 Exportación Portugal,Generación programada P48 Exportación Francia,Generación programada P48 Importación Portugal,Generación programada P48 Importación Francia
0,0,2015-10-01 00:00:00+02:00,117.77,69.49,71.88,1.443650e+09,24984.666667,1003.666667,6012.833333,402.166667,...,61.18,NaN,56.65,25305.0,267.6,182.4,-606.6,NaN,NaN,1200.0
1,1,2015-10-01 01:00:00+02:00,117.09,68.21,65.57,1.443654e+09,23550.833333,899.000000,6013.166667,174.833333,...,59.59,NaN,53.50,23959.0,195.7,-269.5,-1112.5,NaN,NaN,1200.0
2,2,2015-10-01 02:00:00+02:00,114.59,65.34,62.53,1.443658e+09,22648.166667,927.500000,6013.500000,103.833333,...,56.27,49.13,49.69,22873.0,202.1,94.0,-951.0,NaN,NaN,1200.0
3,3,2015-10-01 03:00:00+02:00,116.60,66.53,63.40,1.443661e+09,22203.833333,935.666667,6013.000000,102.000000,...,45.99,45.50,49.10,22550.0,61.3,319.7,-846.3,NaN,NaN,1200.0
4,4,2015-10-01 04:00:00+02:00,122.07,71.03,67.37,1.443665e+09,21987.833333,900.833333,6014.166667,101.666667,...,52.28,49.13,51.25,22017.0,45.1,405.5,-760.5,NaN,NaN,1200.0

In [6]:
total_df = pd.merge(data_total, df_temp_hour, on='date_timestamp')
total_df.rename({'Precio mercado SPOT Diario_y': 'Precio SPOT PT'}, axis=1, inplace=True)
total_df.tail()

,Unnamed: 0,fecha,PVPC_DEF,PVPC_2_PED_NOC,PVPC_ELEC_NOC,date_timestamp,Demanda,Eolica,Nuclear,Solar,...,Precio mercado SPOT Diario_x,Demanda real,Generación prevista Solar,Saldo total interconexiones programa p48,Generación programada P48 Exportación Portugal,Generación programada P48 Exportación Francia,Generación programada P48 Importación Portugal,Generación programada P48 Importación Francia,Precio SPOT PT,date
32338,31442,2019-07-31 20:00:00+02:00,108.27,126.87,126.87,1.564596e+09,31583.333333,6774.666667,6943.500000,1622.166667,...,48.17,31807.0,1715.3,-464.7,-2024.0,NaN,826.3,1200.0,48.17,2019-07-31 18:00:00+00:00
32339,31443,2019-07-31 21:00:00+02:00,109.20,127.81,127.81,1.564600e+09,31693.666667,6979.500000,6952.166667,831.166667,...,48.79,31381.0,842.2,-156.3,-1882.8,NaN,1191.5,1200.0,48.79,2019-07-31 19:00:00+00:00
32340,31444,2019-07-31 22:00:00+02:00,110.68,129.29,129.29,1.564603e+09,31006.000000,6857.500000,6957.166667,702.500000,...,50.17,31831.0,599.7,-640.8,-1947.4,NaN,966.6,1200.0,50.17,2019-07-31 20:00:00+00:00
32341,31445,2019-07-31 23:00:00+02:00,105.84,57.76,60.74,1.564607e+09,28759.333333,6490.500000,6960.166667,690.500000,...,45.19,29588.0,579.6,-1293.1,-2116.7,-5.2,482.8,1200.0,45.19,2019-07-31 21:00:00+00:00
32342,31446,2019-08-01 00:00:00+02:00,112.39,63.66,67.26,1.564610e+09,27546.666667,6010.333333,6960.166667,668.500000,...,50.15,27579.0,595.3,-861.5,-1570.0,NaN,320.5,1200.0,50.15,2019-07-31 22:00:00+00:00

## Precio de Francia

In [7]:
esios = ESIOS(token)

indicators_ = list()
indicators_.append(600)  # Precio mercado SPOT Diario

names = esios.get_names(indicators_)
dfmul, df_list, names = esios.get_multiple_series(indicators_,'fr', start_, end_)
df = dfmul[names]  # get the actual series and neglect the rest of the info

df.head()

Getting the indicators...
Parsing Precio mercado SPOT Diario

                          Precio mercado SPOT Diario
2015-09-30 22:00:00+00:00                      38.56
2015-09-30 23:00:00+00:00                      31.27
2015-10-01 00:00:00+00:00                      30.66
2015-10-01 01:00:00+00:00                      29.14
2015-10-01 02:00:00+00:00                       29.4

In [8]:
df_temp_hour = df
df_temp_hour['date'] = pd.to_datetime(df_temp_hour.index)
df_temp_hour['date_timestamp'] = df_temp_hour['date'].apply(lambda x:  datetime.timestamp(x))
df_temp_hour.head()

/Users/davidcerezallanda/.conda/envs/practicaspy36/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/davidcerezallanda/.conda/envs/practicaspy36/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,Precio mercado SPOT Diario,date,date_timestamp
2015-09-30 22:00:00+00:00,38.56,2015-09-30 22:00:00+00:00,1.443650e+09
2015-09-30 23:00:00+00:00,31.27,2015-09-30 23:00:00+00:00,1.443654e+09
2015-10-01 00:00:00+00:00,30.66,2015-10-01 00:00:00+00:00,1.443658e+09
2015-10-01 01:00:00+00:00,29.14,2015-10-01 01:00:00+00:00,1.443661e+09
2015-10-01 02:00:00+00:00,29.4,2015-10-01 02:00:00+00:00,1.443665e+09

In [9]:
total_df = pd.merge(total_df, df_temp_hour, on='date_timestamp')
total_df.rename({'Precio mercado SPOT Diario': 'Precio SPOT FR'}, axis=1, inplace=True)
total_df.tail()

,Unnamed: 0,fecha,PVPC_DEF,PVPC_2_PED_NOC,PVPC_ELEC_NOC,date_timestamp,Demanda,Eolica,Nuclear,Solar,...,Generación prevista Solar,Saldo total interconexiones programa p48,Generación programada P48 Exportación Portugal,Generación programada P48 Exportación Francia,Generación programada P48 Importación Portugal,Generación programada P48 Importación Francia,Precio SPOT PT,date_x,Precio mercado SPOT Diario,date_y
34130,31442,2019-07-31 20:00:00+02:00,108.27,126.87,126.87,1.564596e+09,31583.333333,6774.666667,6943.500000,1622.166667,...,1715.3,-464.7,-2024.0,NaN,826.3,1200.0,48.17,2019-07-31 18:00:00+00:00,40.43,2019-07-31 18:00:00+00:00
34131,31443,2019-07-31 21:00:00+02:00,109.20,127.81,127.81,1.564600e+09,31693.666667,6979.500000,6952.166667,831.166667,...,842.2,-156.3,-1882.8,NaN,1191.5,1200.0,48.79,2019-07-31 19:00:00+00:00,39.59,2019-07-31 19:00:00+00:00
34132,31444,2019-07-31 22:00:00+02:00,110.68,129.29,129.29,1.564603e+09,31006.000000,6857.500000,6957.166667,702.500000,...,599.7,-640.8,-1947.4,NaN,966.6,1200.0,50.17,2019-07-31 20:00:00+00:00,44.07,2019-07-31 20:00:00+00:00
34133,31445,2019-07-31 23:00:00+02:00,105.84,57.76,60.74,1.564607e+09,28759.333333,6490.500000,6960.166667,690.500000,...,579.6,-1293.1,-2116.7,-5.2,482.8,1200.0,45.19,2019-07-31 21:00:00+00:00,41.74,2019-07-31 21:00:00+00:00
34134,31446,2019-08-01 00:00:00+02:00,112.39,63.66,67.26,1.564610e+09,27546.666667,6010.333333,6960.166667,668.500000,...,595.3,-861.5,-1570.0,NaN,320.5,1200.0,50.15,2019-07-31 22:00:00+00:00,39,2019-07-31 22:00:00+00:00

In [10]:
total_df = total_df.drop(columns=[ 'date_x', 'date_y'])
total_df = total_df.loc[:, ~total_df.columns.str.contains('^Unnamed')]
total_df.head()

,fecha,PVPC_DEF,PVPC_2_PED_NOC,PVPC_ELEC_NOC,date_timestamp,Demanda,Eolica,Nuclear,Solar,Solar_Fotovoltaica,...,Precio mercado SPOT Diario_x,Demanda real,Generación prevista Solar,Saldo total interconexiones programa p48,Generación programada P48 Exportación Portugal,Generación programada P48 Exportación Francia,Generación programada P48 Importación Portugal,Generación programada P48 Importación Francia,Precio SPOT PT,Precio mercado SPOT Diario
0,2015-10-01 00:00:00+02:00,117.77,69.49,71.88,1.443650e+09,24984.666667,1003.666667,6012.833333,402.166667,33.0,...,56.65,25305.0,267.6,182.4,-606.6,NaN,NaN,1200.0,56.65,38.56
1,2015-10-01 01:00:00+02:00,117.09,68.21,65.57,1.443654e+09,23550.833333,899.000000,6013.166667,174.833333,33.0,...,53.50,23959.0,195.7,-269.5,-1112.5,NaN,NaN,1200.0,53.5,31.27
2,2015-10-01 02:00:00+02:00,114.59,65.34,62.53,1.443658e+09,22648.166667,927.500000,6013.500000,103.833333,33.0,...,49.69,22873.0,202.1,94.0,-951.0,NaN,NaN,1200.0,49.69,30.66
3,2015-10-01 03:00:00+02:00,116.60,66.53,63.40,1.443661e+09,22203.833333,935.666667,6013.000000,102.000000,33.0,...,49.10,22550.0,61.3,319.7,-846.3,NaN,NaN,1200.0,49.1,29.14
4,2015-10-01 04:00:00+02:00,122.07,71.03,67.37,1.443665e+09,21987.833333,900.833333,6014.166667,101.666667,33.0,...,51.25,22017.0,45.1,405.5,-760.5,NaN,NaN,1200.0,51.25,29.4

In [13]:
total_df.to_csv('data_total.csv')